### ISSUE TITLE
Latency to be validated in variable_validation

### ISSUE THREAD

**Issue by kristabh** [kristabh/gaze-following-analysis#23]
Check when labs began counting latencies.  Are values as expected?

**Comment by AlexisBlack2g** [comment]
I'm a bit confused about the instructions for latency. According to RR: 
"On each trial, latency was coded as the latency of the first face-to-object shift, such that each infant had a value on each trial for latency to look at both the congruent and incongruent AOIs. "
I would interpret this to mean that each trial should report a latency to both the congruent and incongruent stimulus. I don't think this is the case, though - right? What we're seeing is the latency to the first shift (and whether that was in/congruent)?

**Comment by kristabh** [comment]
Yes, I think you're right and unfortunately this is an error in the RR.  I've changed the wording now (tracked) on the post-registration version for editing.

**Comment by AlexisBlack2g** [comment]
Since we are already discussing the coding of latency with Manitoba and Western Sydney, I reached out about the two trials with very long latencies in these two datasets (one 4165000 - looks like a misplaced decimal in original file; the other 63032310 - less clear what happened here).

**Comment by kristabh** [comment]
@AlexisBlack2g Did these values ever get changed in the data?

**Comment by AlexisBlack2g** [comment]
being tackled by Jessica Hay

**Comment by kristabh** [comment]
Closing and moving discussion of babylab_western_sydney to a new issue
