### ISSUE TITLE
Latencies - babylab-westernsydney - many zero values

### ISSUE THREAD

**Issue by kristabh** [kristabh/gaze-following-analysis#27]
Check in on babylab-westernsydney and bll-umanitoba.  Alexis on it?

**Comment by AlexisBlack2g** [comment]
On it!

**Comment by AlexisBlack2g** [comment]
both labs counted trials where baby began by trial looking at object as 0 latency. Both labs have been instructed that latency is calculated for the first shift from face to object.
Infantlanglab-utk and nusinfantlanguagecentre also reported some 0 latencies, though very few of them. Should I contact them as well? Should we drop these trials?

**Comment by kristabh** [comment]
Zeros are not necessarily errors - it could be that there was a one-frame fixation on the face, and then the shift started immediately to the object.  Might be a good idea to check with the labs, though, to see if this was the case for these, or if the zeros are errors.  If they are real, no need to filter.

**Comment by kristabh** [comment]
bll-manitoba reports not being able to get good reliability on coding.  They have requested their data be excluded.  Noted, and excluded from script.

**Comment by kristabh** [comment]
@AlexisBlack2g any news from babylab-westernsydney on this issue?

**Comment by kristabh** [comment]
Jessica Hay is checking in with babylab-westernsydney

**Comment by kristabh** [comment]
Moved to issue #54
