### ISSUE TITLE
langcog

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#28]
I keep getting an error that langcog is not available for R 3.5.2 (most current version of R). Anyone else?

**Comment by kristabh** [comment]
Did you install langcog like this:

install.packages("devtools")
devtools::install_github("langcog/langcog")

**Comment by AlexisBlack2g** [comment]
sadly yes :/. and restarted R afterwards just in case that was the problem. No luck!

**Comment by AlexisBlack2g** [comment]
(also updated R studio, and restarted afterwards)

**Comment by kristabh** [comment]
Hmm, I have not been having this problem.  I don't think we are using too many functions from langcog, so maybe you can work around it?
