### ISSUE TITLE
latencies - keeping in the NAs?

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#29]
The code (02_variable_validation) was pruning out all of latency NA trials. Do we want to filter those trials out?  (it cuts the data by over 1500 trials).

**Comment by kristabh** [comment]
I think we want to keep these for now, and filter them out as needed at the point of analysis. We didn't pre-register anything about filtering out these trials in general, I don't think.

**Comment by AlexisBlack2g** [comment]
Great - fixed.
