### ISSUE TITLE
d_first_meta - what should 'n' reflect?

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#33]
probably doesn't matter, but just to keep data clean:

right now the 'n' reflects only the number of trials that were congruent (because the number of trials that were incongruent are filtered out). 

This seems confusing for the data - we'd either (probably?) want the n to reflect the total number of trials that were included, or just remove n from data frame (to avoid confusion)?

**Comment by kristabh** [comment]
I have made a lot of changes to this script now.  That n is just used to calculate some needed values, and now gets removed from the dataframe by the end of the pipes.

**Comment by AlexisBlack2g** [comment]
great - thanks!
