### ISSUE TITLE
subid's same, diff labs

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#38]
I noticed a weird outlier in a histogram - it's because there is one subid that is the same across labs and it was getting doubled in a grouping operation. One way to ensure this doesn't happen is to append the lab to each subid. Should I do that?  Would implement upstream in 02 somewhere

**Comment by kristabh** [comment]
Hmm, interesting. Yes, in this case I think that appending would make sense.

**Comment by AlexisBlack2g** [comment]
done!
