### ISSUE TITLE
ybg038 - handcoded and eye tracking data

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#39]
This participant has both eye-tracking and hardcoding.  I assume this was just a check - but I'm confused about the other 'handcoded' data from nusinfantlanguagecentre. These are completely separate participants that were handcoded?  (the subids are different, so I assume so)

**Comment by kristabh** [comment]
This lab apparently hand codes data when they are having trouble with the eye tracker...  But we can double check with Leher

**Comment by AlexisBlack2g** [comment]
I removed the eye-tracking data from this participant for now (assuming that the reason it was hand-coded was some problem with the eye-tracking)
