### ISSUE TITLE
session error for language/age criteria?

### ISSUE THREAD

**Issue by melsod** [kristabh/gaze-following-analysis#43]
Related to issues #21, #36. There is a lack of consistency in whether babies that are neither bilingual nor monolingual (i.e. "other" according to our criteria), and out-of-age babies, get marked as session errors or not. My preference is to NOT mark them as a session error and just do the exclusion based on the listed age-in-days and/or language categorization, as appropriate. The reason is that if someone later wants to run a secondary analysis with different criteria, they don't have to go back through the "session error" participants to figure out which ones can be included. The following labs listed one or both of language/age exclusions as a "session error":

Georgetown (age)
Concordia (lang)
UPF-Barcelona (age, lang)

**Comment by kristabh** [comment]
Agreed.  I have already gone through session errors and removed these babies from session-level exclusion.
