### ISSUE TITLE
babylab_western_sydney copy-paste error?

### ISSUE THREAD

**Issue by melsod** [kristabh/gaze-following-analysis#44]
There is an identical comment (about grandmother hearing loss) and an identical typo ("Nno") in different but comparable cells of the two monolingual files, so that if you compare the two documents seems to indicate there was some kind of copy-paste error in one of the two spreadsheets (hard to describe, easy to see).

**Comment by kristabh** [comment]
Closing and moving discussion of babylab_western_sydney to a new issue
