### ISSUE TITLE
Lang exposure, languages

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#52]
Probably filtered, but noting just in case:

(1) a few infants have no percent exposure noted

(2) Also noticed that Ukrainian is misspelled as Ukrainean for one infant - so should do check of languages listed to make sure there aren't duplicates due to spelling errors (not relevant for our analyses but might be an exploratory analysis for someone down the road)

**Comment by Joscelinrocha** [comment]
I added this to the 02.variable_validation.Rmd but I have some questions I wanted to run with you two:

**for lang2** => there is a child whose language is "chinese". We have been really consistent at having the different dialects of this language separated except for this kid. Should the lab be contacted to ask for more info maybe they know the dialect? this is a western Sydney baby so maybe not necessary to reach out?
There is also a child who has "Newfoundland English" as their L2. In the script, we changed that to "english". Should this still be the case? If yes, should the L1 English % be merged with L2 English %?. The child also has an L3 which if we merge would be moved to L2. 

**for lang3** => there is one baby who has "dialect" as their L3 and another one who has "dialects". Should I leave them like they are or group them? under the same umbrella, there is a child who has "cantonese hokkien". These are two different dialects counted as one L3, relabel it "dialects"? or...?

**Comment by kristabh** [comment]
Ideally labs would have provided specific dialect info, but this is probably what the parent reported.  So I'd leave things like "Chinese" and "dialect" for now.  We don't really need to spend too much time cleaning up the language names.  But I do think that for the different dialects of English, those could be merged for the purposes of gaze following - that was more relevant to MB1.
